version: "3.9"

services:
  flaskapp:
    build: .
    container_name: homestation
    ports:
      - "4999:4999"
    volumes:
      - /volume1/video:/app/videos:ro
    environment:
      - FLASK_ENV=development
    env_file: 
      - .env

